--[[
╔══════════════════════════════════════════════════════════════════╗
║                 VehicleSpawnArea — Framework                     ║
║                    shared/framework.lua                          ║
╠══════════════════════════════════════════════════════════════════╣
║  Auto-detects the active framework and provides a unified API    ║
║  for retrieving player job data on both the client and server.   ║
║                                                                  ║
║  Detection order (first match wins):                             ║
║    1. QBox       — qbx_core                                      ║
║    2. QBCore     — qb-core                                       ║
║    3. ESX        — es_extended                                   ║
║    4. Standalone — no framework found                            ║
║                                                                  ║
║  Do NOT edit this file unless you are adding framework support.  ║
╚══════════════════════════════════════════════════════════════════╝
--]]

--- Global framework table. Exposes Framework.name and Framework.GetPlayerJob().
Framework      = {}
Framework.name = 'standalone'

-- ============================================================
-- AUTO-DETECTION
-- ============================================================

--- Detects which framework (if any) is running and sets Framework.name.
--- QBox is checked first because it exposes a QBCore-compatible API surface
--- but must be identified separately to use the correct export calls.
local function DetectFramework()
    if GetResourceState('qbx_core') == 'started' then
        Framework.name = 'qbox'
    elseif GetResourceState('qb-core') == 'started' then
        Framework.name = 'qbcore'
    elseif GetResourceState('es_extended') == 'started' then
        Framework.name = 'esx'
    else
        Framework.name = 'standalone'
    end

    if Config.Debug then
        print(('[VehicleSpawnArea] Framework detected: %s'):format(Framework.name))
    end
end

DetectFramework()

-- ============================================================
-- FRAMEWORK OBJECT CACHE
-- ============================================================

--- Cached reference to the framework's core object.
--- Retrieved once and reused to avoid repeated export calls.
local cachedObj = nil

--- Returns the framework's core object, fetching and caching it on first call.
--- Returns nil for standalone or QBox (which use direct exports instead).
---@return table|nil
local function GetFrameworkObject()
    if cachedObj then return cachedObj end

    if Framework.name == 'esx' then
        -- ESX exposes its shared object via an export
        cachedObj = exports['es_extended']:getSharedObject()
    elseif Framework.name == 'qbcore' then
        -- QBCore exposes its core object via an export
        cachedObj = exports['qb-core']:GetCoreObject()
    elseif Framework.name == 'qbox' then
        -- QBox uses direct exports rather than a shared object;
        -- store the export table itself as a convenient reference
        cachedObj = exports['qbx_core']
    end

    return cachedObj
end

-- ============================================================
-- CLIENT-SIDE: GetPlayerJob
-- ============================================================
--[[
  Returns the local player's current job and grade.
  Only compiled and available on the client (not the server).

  Return format: { name = 'police', grade = 2 }
  Returns nil if the framework provides no job data or in standalone mode.
--]]

if not IsDuplicityVersion() then

    --- Retrieves the local player's job from whichever framework is active.
    ---@return table|nil  { name: string, grade: number } or nil in standalone mode
    function Framework.GetPlayerJob()

        if Framework.name == 'esx' then
            local obj        = GetFrameworkObject()
            if not obj then return nil end
            local playerData = obj.GetPlayerData()

            if playerData and playerData.job then
                return {
                    name  = playerData.job.name,
                    grade = playerData.job.grade or 0,
                }
            end

        elseif Framework.name == 'qbcore' then
            local obj        = GetFrameworkObject()
            if not obj then return nil end
            local playerData = obj.Functions.GetPlayerData()

            if playerData and playerData.job then
                return {
                    name  = playerData.job.name,
                    -- QBCore nests the numeric grade under job.grade.level
                    grade = playerData.job.grade and playerData.job.grade.level or 0,
                }
            end

        elseif Framework.name == 'qbox' then
            -- QBox mirrors QBCore's data structure
            local playerData = exports['qbx_core']:GetPlayerData()

            if playerData and playerData.job then
                return {
                    name  = playerData.job.name,
                    grade = playerData.job.grade and playerData.job.grade.level or 0,
                }
            end

        else
            -- Standalone: no job system available
            return nil
        end

        return nil
    end

end

-- ============================================================
-- SERVER-SIDE: GetPlayerJob
-- ============================================================
--[[
  Returns a specific player's job and grade by their server source ID.
  Only compiled and available on the server (not the client).

  Return format: { name = 'police', grade = 2 }
  Returns nil if the framework provides no job data or in standalone mode.
--]]

if IsDuplicityVersion() then

    --- Retrieves a player's job on the server using their source ID.
    ---@param source number  The player's server source ID
    ---@return table|nil     { name: string, grade: number } or nil in standalone mode
    function Framework.GetPlayerJob(source)

        if Framework.name == 'esx' then
            local obj     = GetFrameworkObject()
            if not obj then return nil end
            local xPlayer = obj.GetPlayerFromId(source)

            if xPlayer and xPlayer.getJob then
                local job = xPlayer.getJob()
                return {
                    name  = job.name,
                    grade = job.grade or 0,
                }
            end

        elseif Framework.name == 'qbcore' then
            local obj    = GetFrameworkObject()
            if not obj then return nil end
            local player = obj.Functions.GetPlayer(source)

            if player and player.PlayerData and player.PlayerData.job then
                return {
                    name  = player.PlayerData.job.name,
                    grade = player.PlayerData.job.grade and player.PlayerData.job.grade.level or 0,
                }
            end

        elseif Framework.name == 'qbox' then
            -- QBox exposes a GetPlayer export that returns the same data structure as QBCore
            local player = exports['qbx_core']:GetPlayer(source)

            if player and player.PlayerData and player.PlayerData.job then
                return {
                    name  = player.PlayerData.job.name,
                    grade = player.PlayerData.job.grade and player.PlayerData.job.grade.level or 0,
                }
            end

        else
            -- Standalone: no job system available; callers handle nil gracefully
            return nil
        end

        return nil
    end

end
